# bootstrap.ps1 — Initialize a new LifeOS instance (Windows PowerShell 7+)
# Run from instance root directory (where lifeos.yaml will live)

$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$SystemDir = Split-Path -Parent (Split-Path -Parent $ScriptDir)
$InstanceDir = Split-Path -Parent $SystemDir

Write-Host "=== LifeOS Instance Bootstrap ===" -ForegroundColor Cyan
Write-Host "Instance dir: $InstanceDir"
Write-Host "System dir: $SystemDir"
Write-Host ""

# --- Prerequisites Check ---
Write-Host "[1/7] Checking prerequisites..." -ForegroundColor Yellow

if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
    Write-Error "git not found. Install git first."
    exit 1
}

if (-not (Get-Command glab -ErrorAction SilentlyContinue)) {
    Write-Error "glab not found. Install via: winget install GLab.GLab"
    exit 1
}

$glabAuth = glab auth status 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Error "glab not authenticated. Run: glab auth login"
    exit 1
}

Write-Host "  git, glab installed and authenticated" -ForegroundColor Green

# --- Create Directory Structure ---
Write-Host "[2/7] Creating directory structure..." -ForegroundColor Yellow

$dirs = @(
    "domains",
    "wiki\_meta", "wiki\_raw", "wiki\concepts", "wiki\entities",
    "wiki\decisions", "wiki\projects", "wiki\synthesis",
    "raw\papers", "raw\transcripts", "raw\exports", "raw\screenshots",
    "secrets"
)

foreach ($dir in $dirs) {
    $path = Join-Path $InstanceDir $dir
    if (-not (Test-Path $path)) {
        New-Item -ItemType Directory -Path $path -Force | Out-Null
    }
}

Write-Host "  Directory structure created" -ForegroundColor Green

# --- Create lifeos.yaml ---
Write-Host "[3/7] Creating instance configuration..." -ForegroundColor Yellow

$lifeosPath = Join-Path $InstanceDir "lifeos.yaml"
if (-not (Test-Path $lifeosPath)) {
    $version = Get-Content (Join-Path $SystemDir "VERSION") -Raw
    $version = $version.Trim()
    
    $yaml = @"
# lifeos.yaml - Instance Configuration
# Generated by bootstrap on $(Get-Date -Format "yyyy-MM-ddTHH:mm:ssZ")

instance:
  name: "My LifeOS"
  owner: "dewdad"
  gitlab_project: "dewdad/lifeos-personal"
  system_version: "$version"

identity:
  timezone: "Asia/Jerusalem"
  locale: "en-US"

domains: []
  # Add domains here, then create matching folders in domains/
  # Example:
  # - health
  # - finance
  # - career
  # - learning

agent_config:
  default_branch: main
  mr_required: true
  auto_merge: false
  stale_wip_timeout_minutes: 30
  max_parallel_agents: 3

scheduling:
  source_pull: "0 3 * * *"
  wiki_lint: "0 4 * * *"
  morning_brief: "0 7 * * *"
  weekly_review: "0 20 * * 0"
"@
    Set-Content -Path $lifeosPath -Value $yaml -Encoding UTF8
    Write-Host "  lifeos.yaml created" -ForegroundColor Green
} else {
    Write-Host "  ~ lifeos.yaml already exists, skipping" -ForegroundColor DarkGray
}

# --- Create .gitignore ---
Write-Host "[4/7] Creating .gitignore..." -ForegroundColor Yellow

$gitignorePath = Join-Path $InstanceDir ".gitignore"
$gitignore = @"
# Secrets (local-only)
secrets/*
!secrets/.gitkeep
!secrets/README.md

# OS files
.DS_Store
Thumbs.db
desktop.ini

# Editor
.vscode/
.idea/
*.swp
*.swo

# Obsidian (local-only settings)
.obsidian/workspace.json
.obsidian/workspace-mobile.json
"@
Set-Content -Path $gitignorePath -Value $gitignore -Encoding UTF8
Write-Host "  .gitignore created" -ForegroundColor Green

# --- Create secrets ---
Write-Host "[5/7] Creating secrets directory..." -ForegroundColor Yellow

$secretsReadme = Join-Path $InstanceDir "secrets\README.md"
if (-not (Test-Path $secretsReadme)) {
    $readme = @"
# Secrets

This directory stores credentials and tokens referenced by source configs.
It is .gitignore'd and never committed.

Create files here as referenced by auth_ref in your source configs.
"@
    Set-Content -Path $secretsReadme -Value $readme -Encoding UTF8
}
$gitkeep = Join-Path $InstanceDir "secrets\.gitkeep"
if (-not (Test-Path $gitkeep)) { New-Item -ItemType File -Path $gitkeep -Force | Out-Null }
Write-Host "  secrets directory configured" -ForegroundColor Green

# --- Create wiki index ---
Write-Host "[6/7] Creating wiki starter pages..." -ForegroundColor Yellow

$wikiIndex = Join-Path $InstanceDir "wiki\index.md"
if (-not (Test-Path $wikiIndex)) {
    $index = @"
---
title: "Wiki Index"
category: meta
created: "$(Get-Date -Format 'yyyy-MM-dd')"
---

# Knowledge Base

Welcome to your LifeOS knowledge base.

## Sections

- [[concepts/]] - Ideas, patterns, techniques
- [[entities/]] - People, tools, organizations
- [[decisions/]] - Architecture Decision Records
- [[projects/]] - Per-project knowledge spaces
- [[synthesis/]] - Cross-domain analyses
"@
    Set-Content -Path $wikiIndex -Value $index -Encoding UTF8
    Write-Host "  wiki/index.md created" -ForegroundColor Green
}

# --- Create .gitlab-ci.yml ---
Write-Host "[7/7] Creating CI configuration..." -ForegroundColor Yellow

$ciPath = Join-Path $InstanceDir ".gitlab-ci.yml"
if (-not (Test-Path $ciPath)) {
    $ci = @"
# LifeOS Instance CI/CD Pipeline
include:
  - local: '.system/templates/ci/wiki-pipeline.yml'
  - local: '.system/templates/ci/maintenance-pipeline.yml'

stages:
  - validate
  - maintain
  - publish

variables:
  WIKI_DIR: "wiki"
  DOMAINS_DIR: "domains"
"@
    Set-Content -Path $ciPath -Value $ci -Encoding UTF8
    Write-Host "  .gitlab-ci.yml created" -ForegroundColor Green
}

Write-Host ""
Write-Host "=== Bootstrap Complete ===" -ForegroundColor Cyan
Write-Host ""
Write-Host "Next steps:"
Write-Host "  1. Edit lifeos.yaml with your settings"
Write-Host "  2. Create domain folders: New-Item -ItemType Directory domains/<name>"
Write-Host "  3. Add source configs: domains/<name>/sources.yaml"
Write-Host "  4. Run: .system/scripts/setup/configure-gitlab.sh"
Write-Host "  5. Initial commit: git add . && git commit -m 'feat: initialize LifeOS'"
Write-Host "  6. Push: git push -u origin main"
