#!/usr/bin/env bash
set -euo pipefail

# bootstrap.sh — Initialize a new LifeOS instance
# Run from instance root directory (where lifeos.yaml will live)

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SYSTEM_DIR="$(cd "${SCRIPT_DIR}/../.." && pwd)"
INSTANCE_DIR="$(cd "${SYSTEM_DIR}/.." && pwd)"

echo "=== LifeOS Instance Bootstrap ==="
echo "Instance dir: ${INSTANCE_DIR}"
echo "System dir: ${SYSTEM_DIR}"
echo ""

# --- Prerequisites Check ---
echo "[1/7] Checking prerequisites..."

if ! command -v git &> /dev/null; then
  echo "ERROR: git not found. Install git first."
  exit 1
fi

if ! command -v glab &> /dev/null; then
  echo "ERROR: glab not found. Run: .system/scripts/setup/install-glab.sh"
  exit 1
fi

if ! glab auth status &> /dev/null; then
  echo "ERROR: glab not authenticated. Run: glab auth login"
  exit 1
fi

echo "  ✓ git, glab installed and authenticated"

# --- Create Directory Structure ---
echo "[2/7] Creating directory structure..."

mkdir -p "${INSTANCE_DIR}/domains"
mkdir -p "${INSTANCE_DIR}/wiki/_meta"
mkdir -p "${INSTANCE_DIR}/wiki/_raw"
mkdir -p "${INSTANCE_DIR}/wiki/concepts"
mkdir -p "${INSTANCE_DIR}/wiki/entities"
mkdir -p "${INSTANCE_DIR}/wiki/decisions"
mkdir -p "${INSTANCE_DIR}/wiki/projects"
mkdir -p "${INSTANCE_DIR}/wiki/synthesis"
mkdir -p "${INSTANCE_DIR}/raw/papers"
mkdir -p "${INSTANCE_DIR}/raw/transcripts"
mkdir -p "${INSTANCE_DIR}/raw/exports"
mkdir -p "${INSTANCE_DIR}/raw/screenshots"
mkdir -p "${INSTANCE_DIR}/secrets"

echo "  ✓ Directory structure created"

# --- Create lifeos.yaml (if not exists) ---
echo "[3/7] Creating instance configuration..."

if [ ! -f "${INSTANCE_DIR}/lifeos.yaml" ]; then
  OWNER=$(glab auth status 2>&1 | grep -oP 'Logged in to .+ as \K\w+' || echo "unknown")
  
  cat > "${INSTANCE_DIR}/lifeos.yaml" << EOF
# lifeos.yaml — Instance Configuration
# Generated by bootstrap on $(date -u +%Y-%m-%dT%H:%M:%SZ)

instance:
  name: "My LifeOS"
  owner: "${OWNER}"
  gitlab_project: "${OWNER}/lifeos-personal"
  system_version: "$(cat ${SYSTEM_DIR}/VERSION)"

identity:
  timezone: "UTC"
  locale: "en-US"

domains: []
  # Add domains here, then create matching folders in domains/
  # Example:
  # - health
  # - finance
  # - career
  # - learning

agent_config:
  default_branch: main
  mr_required: true
  auto_merge: false
  stale_wip_timeout_minutes: 30
  max_parallel_agents: 3

scheduling:
  source_pull: "0 3 * * *"
  wiki_lint: "0 4 * * *"
  morning_brief: "0 7 * * *"
  weekly_review: "0 20 * * 0"
EOF
  echo "  ✓ lifeos.yaml created (edit with your settings)"
else
  echo "  ~ lifeos.yaml already exists, skipping"
fi

# --- Create .gitignore ---
echo "[4/7] Creating .gitignore..."

cat > "${INSTANCE_DIR}/.gitignore" << 'EOF'
# Secrets (local-only)
secrets/*
!secrets/.gitkeep
!secrets/README.md

# OS files
.DS_Store
Thumbs.db
desktop.ini

# Editor
.vscode/
.idea/
*.swp
*.swo

# Obsidian (local-only settings)
.obsidian/workspace.json
.obsidian/workspace-mobile.json
EOF

echo "  ✓ .gitignore created"

# --- Create secrets placeholder ---
echo "[5/7] Creating secrets directory..."

cat > "${INSTANCE_DIR}/secrets/README.md" << 'EOF'
# Secrets

This directory stores credentials and tokens referenced by source configs.
It is .gitignore'd and never committed.

## Setup

Create files here as referenced by `auth_ref` in your source configs:

```
secrets/
├── fitbit_token        ← API token for Fitbit
├── youtube_api_key     ← YouTube Data API key
├── gmail_credentials   ← Gmail IMAP credentials
└── ...
```

## Format

Each file contains the raw credential value (no JSON wrapper unless the source script expects it).
EOF

touch "${INSTANCE_DIR}/secrets/.gitkeep"
echo "  ✓ secrets directory configured"

# --- Create wiki index ---
echo "[6/7] Creating wiki starter pages..."

if [ ! -f "${INSTANCE_DIR}/wiki/index.md" ]; then
  cat > "${INSTANCE_DIR}/wiki/index.md" << 'EOF'
---
title: "Wiki Index"
category: meta
created: "2026-05-10"
---

# Knowledge Base

Welcome to your LifeOS knowledge base.

## Sections

- [[concepts/]] — Ideas, patterns, techniques
- [[entities/]] — People, tools, organizations
- [[decisions/]] — Architecture Decision Records
- [[projects/]] — Per-project knowledge spaces
- [[synthesis/]] — Cross-domain analyses

## Recent Activity

_Updated automatically by agents._
EOF
  echo "  ✓ wiki/index.md created"
fi

if [ ! -f "${INSTANCE_DIR}/wiki/_meta/taxonomy.md" ]; then
  cat > "${INSTANCE_DIR}/wiki/_meta/taxonomy.md" << 'EOF'
---
title: "Taxonomy"
category: meta
---

# Tag Taxonomy

Controlled vocabulary for wiki page tags.

## Categories
- `concept` — Abstract ideas and patterns
- `entity` — Concrete things (people, tools, orgs)
- `decision` — Choices made with rationale
- `project` — Project-specific knowledge
- `synthesis` — Cross-cutting analysis

## Domain Tags
<!-- Add domain-specific tags here as domains are configured -->
EOF
  echo "  ✓ wiki/_meta/taxonomy.md created"
fi

# --- Create .gitlab-ci.yml ---
echo "[7/7] Creating CI configuration..."

if [ ! -f "${INSTANCE_DIR}/.gitlab-ci.yml" ]; then
  cat > "${INSTANCE_DIR}/.gitlab-ci.yml" << 'EOF'
# LifeOS Instance CI/CD Pipeline
# Includes reusable fragments from .system/

include:
  - local: '.system/templates/ci/wiki-pipeline.yml'
  - local: '.system/templates/ci/maintenance-pipeline.yml'

stages:
  - validate
  - maintain
  - publish

variables:
  WIKI_DIR: "wiki"
  DOMAINS_DIR: "domains"
EOF
  echo "  ✓ .gitlab-ci.yml created"
fi

echo ""
echo "=== Bootstrap Complete ==="
echo ""
echo "Next steps:"
echo "  1. Edit lifeos.yaml with your settings (timezone, domains)"
echo "  2. Create domain folders: mkdir -p domains/<name>"
echo "  3. Add source configs: domains/<name>/sources.yaml"
echo "  4. Run: .system/scripts/setup/configure-gitlab.sh (creates labels & board)"
echo "  5. Initial commit: git add . && git commit -m 'feat: initialize LifeOS'"
echo "  6. Push: git push -u origin main"
